tpximpact/council-digital-site-notice

util/client.ts

Ticket: https://tpximpact.atlassian.net/browse/DSNPI-132?atlOrigin=eyJpIjoiMGRjYTI5MDM3NWE0NDk4MTllM2E3OThmZmQwMWQwNGUiLCJwIjoiaiJ9

filter isActive

---

src/styles/application.scss

Ticket: https://tpximpact.atlassian.net/browse/DSNPI-208?atlOrigin=eyJpIjoiOTI4YmJiYjNmNWFmNDE5NDllZmRkNDZjZjM1NjQ2MGQiLCJwIjoiaiJ9

add max-width

---

sanity/schemas/planningApplication.ts

https://tpximpact.atlassian.net/browse/DSNPI-174

makes sanity address optional

---

src/components/process/index.tsx

Ticket: https://tpximpact.atlassian.net/browse/DSNPI-213?atlOrigin=eyJpIjoiZGQ4ODY1NzA0MWY5NGY5MDlmMzUzMmMxZTdkZjE2ODciLCJwIjoiaiJ9

fixing spelling

---

sanity/schemas/planningApplication.ts

Ticket:| https://tpximpact.atlassian.net/browse/DSNPI-209?atlOrigin=eyJpIjoiZWEwNWExMTM1OTZiNDAyMzk3MDM0NjJkMzE3M2RiZWQiLCJwIjoiaiJ9

changing dropdown to radio

---

src/components/process/index.tsx

Ticket: https://tpximpact.atlassian.net/browse/DSNPI-211?atlOrigin=eyJpIjoiZDNmNGUyYjBiZGE2NGM0NWFhZjVkNDNlYjM3YjFkMGUiLCJwIjoiaiJ9

remove deadline when not consultation

---

src/components/process/index.tsx
src/styles/application.scss
util/applicationHelper.tsx

Ticket: https://tpximpact.atlassian.net/browse/DSNPI-207?atlOrigin=eyJpIjoiMmM3NWVmNDkxYzc0NDRkZWI5YzYzNDc3MzNhYTQ0MzYiLCJwIjoiaiJ9
With the merges today, we lost one ticket that I fixed here
Ticket: https://tpximpact.atlassian.net/browse/DSNPI-214?atlOrigin=eyJpIjoiZjMyMWRjNWUyN2U4NGMxOThiNWYzMGQwNGFlM2I4NjciLCJwIjoiaiJ9

fix button overlap and fix merge

---

util/description-detail.tsx

[Ticket 251](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15/?assignee=62a6f3cb6085950068acebf7&selectedIssue=DSNPI-251)
Replaces text in description detail with the text from the figma designs. Designs matched to the text above it for consistency.

DSNPI 251/replace text

---

src/styles/home.scss

ticket: https://tpximpact.atlassian.net/browse/DSNPI-252?atlOrigin=eyJpIjoiN2IyMzhhN2M0ZjY0NGE0Y2E0YjBjODMzNWY4YTA2YWEiLCJwIjoiaiJ9

fix spacing on heading

---

src/components/check-answers/index.tsx

Ticket: https://tpximpact.atlassian.net/browse/DSNPI-325?atlOrigin=eyJpIjoiOTIyM2YwMTZiNTMyNDI0ODk5NGYyZGExN2M1NTE2MGEiLCJwIjoiaiJ9

personal details

---

sanity/schemas/planningApplication.ts

Ticket: https://tpximpact.atlassian.net/browse/DSNPI-292
Bobbu asked to explain how the user should write the application number when it's wrong

add explanation tip for regex

---

src/app/(main)/planning-applications/[id]/thank-you/page.tsx

ticket: https://tpximpact.atlassian.net/browse/DSNPI-361?atlOrigin=eyJpIjoiYzljY2RlMTY5MTgyNDkzMmIxOGZhMmM4YzU4MjU0NWIiLCJwIjoiaiJ9

fix broken link

---

public/assets/icons/index.js
src/components/feelings/index.tsx
src/styles/feedback.scss

ticket: https://tpximpact.atlassian.net/browse/DSNPI-326?atlOrigin=eyJpIjoiMDIxZjVkNGUxYmEzNDEzNTkwNDhlMTNjNzViMmYxMDciLCJwIjoiaiJ9

add accessibility to sentimental feedback

---

__tests__/index.test.js
__tests__/snapshot.js
src/app/(main)/layout.tsx
src/app/(main)/page.tsx

ticket: https://tpximpact.atlassian.net/browse/DSNPI-365?atlOrigin=eyJpIjoiMjkxZjU0ODMwOWJlNDJiYThlZjA2Y2E1YzYxMDIyMWEiLCJwIjoiaiJ9
In this ticket I added the search and page params. We update in the search location and change pages, and useEffect.

add pagination url

---

__tests__/__snapshots__/snapshot.js.snap
sanity/schemas/planningApplication.ts
src/app/(main)/concern-info/page.tsx
src/app/(main)/page.tsx
src/components/populate-button/index.tsx
src/styles/feedback.scss

this branch is relate to multiple fixes that Bobbu suggest:
[Ticket](https://tpximpact.atlassian.net/browse/DSNPI-337?atlOrigin=eyJpIjoiMGIxZjU1OGJiN2M5NDRjNmI4NzRlMDdjZTU3YTJmZmIiLCJwIjoiaiJ9) The concern page is inside a folder and has page
[Ticket](https://tpximpact.atlassian.net/browse/DSNPI-292?atlOrigin=eyJpIjoiZmIwZjczOTM1YjRjNDFiYjhhOTcwMjE4MWY0ZmZiODgiLCJwIjoiaiJ9) Regex is not case sensitive for letter. I changed a document and was working fine
[Ticket](https://tpximpact.atlassian.net/browse/DSNPI-326?atlOrigin=eyJpIjoiMWYxNTRhZDI5ZDc0NDU2YzgxNTk3NmIyZWEzMWI1ODgiLCJwIjoiaiJ9) The sentiment button has focus now
[Ticket](https://tpximpact.atlassian.net/browse/DSNPI-362?atlOrigin=eyJpIjoiYWI3MTgzNTcwNzBkNDYzYzk5YWVjM2VjZjA3ODA0YjkiLCJwIjoiaiJ9) And I follow bobbu suggestions for …

Dsnpi 326/sentiment style

---

src/app/(main)/page.tsx

ticket: https://tpximpact.atlassian.net/browse/DSNPI-365?atlOrigin=eyJpIjoiZGYxYjg5OGRhNDZlNDNkNDhjZDA1NzA5NzFkYmY4ZDEiLCJwIjoiaiJ9
Fix this search params

fix search params

---

.husky/pre-commit
package.json
yarn.lock

protects commits by running tests and linting

adds husky

---

__tests__/__snapshots__/snapshot.js.snap
src/app/(main)/page.tsx
src/components/banner/index.tsx

Ticket: https://tpximpact.atlassian.net/browse/DSNPI-342?atlOrigin=eyJpIjoiNDBjOWZmOTFjZWVmNGU2NDg1NjgwMDRiOTA1MDI1NzgiLCJwIjoiaiJ9
I think we will be able to test when we merge into main

fix acessibility

---

sanity/schemas/globalContent.ts

ticket: https://tpximpact.atlassian.net/browse/DSNPI-411?atlOrigin=eyJpIjoiNWJmMTNiMmFmYTFiNGJhOTk0NjA5MDRlNDJkOWRjZTgiLCJwIjoiaiJ9

add help text to global content

---

package.json
sanity.cli.ts

Quick eslint fix as I was unable to push commits without changing the lint command and fixing the issues it flagged.

Fix eslint

---

src/app/api/application/uniform/route.ts
src/app/api/applications/uniform/route.ts
src/app/api/checkAllowedUpdateFields.ts

ticket: https://tpximpact.atlassian.net/browse/DSNPI-403

add no updates

---

.gitignore

add .env* to gitignore

---

package-lock.json
package.json
sanity/schemas/planningApplication.ts
yarn.lock

ticket: https://tpximpact.atlassian.net/browse/DSNPI-698?atlOrigin=eyJpIjoiZDA2NzA4MTljNjUxNGQ3NDljNjdlZmVmN2FlZTdmODkiLCJwIjoiaiJ9

add required field for status

---

sanity/schemas/globalContent.ts
src/app/(main)/planning-applications/[id]/feedback/page.tsx
src/components/about/index.tsx
src/components/process/index.tsx

[Ticket 817](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?assignee=62a6f3cb6085950068acebf7&selectedIssue=DSNPI-817)
Add global content field to enable/disable comments - disabling it will hide comment button and redirect users away from the comment flow if they attempt to access it via URL.
n.b. This does not include setting the applicationDocumentsUrl link to Public Access - waiting on a response before addressing that.

DSNPI 817 - enable/disable comments

---

package.json
src/app/(studio)/studio/[[...index]]/page.tsx
yarn.lock

Updated the entire sanity stack to fix the build errors. We had two errors one local and another on deploy this should fix them both. 🤞

update everything to fix build

---

.eslintrc.json
.gitignore
.storybook/main.ts
.storybook/preview.ts
package.json
src/app/(main)/layout.tsx
src/app/layout.tsx
src/components/GovUkInitAll/GovUkInitAll.mdx
src/components/GovUkInitAll/GovUkInitAll.tsx
src/components/GovUkInitAll/index.ts
src/styles/app.scss
src/types/global.d.ts
src/types/index.d.ts
yarn.lock

- adding in storybook (no stories yet)
- upgrade govuk frontend
- update layout to use the `GovUkInitAll` component from DPR

01 - DSN style fixes 

---

__tests__/api/application.test.ts
__tests__/api/applications.test.ts
src/app/api/application/route.ts
src/app/api/applications/route.ts

https://tpximpact.atlassian.net/browse/DSNPI-944

DSNPI-944 dsn update post endpoint to remove uniform from the url

---

__e2e__/accessibility.spec.ts
__tests__/__snapshots__/snapshot.js.snap
__tests__/header.test.js
package.json
src/app/(main)/layout.tsx
src/app/(main)/page.tsx
src/app/(main)/planning-applications/[id]/feedback/instructions.tsx
src/app/(main)/planning-applications/[id]/thank-you/page.tsx
src/app/lib/description.tsx
src/components/button/index.tsx
src/components/check-answers/index.tsx
src/components/formSearch/index.tsx
src/components/header/index.tsx
src/components/imageGallery/index.tsx
src/components/input/index.tsx
src/components/text-area/index.tsx
src/styles/05-objects/_button.scss
src/styles/06-components/_comment-check-answers.scss
src/styles/06-components/_image-gallery.scss
src/styles/app.scss
yarn.lock

Github seemed to cache the first PR I made where I accidentally pointed it to main instead of staging, I'm hoping this PR wont trigger that 'memory'!
I was wrong - we'll just have to ignore the branch protection test as it doesn't apply to this PR!
First pass to get ahead of the e2e and get some of the smaller ones. https://tpximpact.atlassian.net/browse/DSNPI-987

DSNPI-987 dsn final accessibility sanity check before resubmission (tests do pass!)

---

__tests__/index.test.js
__tests__/snapshot.js

Linting error not quite sure how it got in there but its blocking #233 !

Fix for linting error blocking #233!

---

src/components/planning-application-list/index.tsx

https://tpximpact.atlassian.net/browse/DSNPI-972
Based on the ticket testing giving the listing page h3's!

DSNPI-972 Listing page give planning applications h3 headings

---

src/components/details/index.tsx

Remove `role=definition` from details component

DSNPI-983 dsn find planning app near you

---

src/components/check-answers/index.tsx
src/styles/06-components/_comment-check-answers.scss
src/styles/app.scss

Updated the comment summary page to the govuk summary list complete with blue links.

DSNPI-982 comment review definition list

---

src/components/feedback-information/index.tsx

Put the correct class on the headers so their bold

DSNPI-976 dsn heading structure comments flow

---

src/app/(main)/page.tsx
src/app/(main)/planning-applications/[id]/thank-you/page.tsx
src/app/lib/description.tsx
src/components/about/index.tsx
src/components/banner/index.tsx
src/components/cookies/index.tsx
src/components/feedback-information/index.tsx
src/components/process/index.tsx

[Ticket 1034
](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?selectedIssue=DSNPI-1034)
Remove target="_blank" from the whole application so all links open within the same tab.

DSNPI 1034 / WCAG feedback - Stop links opening in a new tab

---

src/app/(main)/api-doc/page.tsx
src/app/(main)/concern-info/page.tsx
src/app/(main)/cookie-policy/page.tsx
src/app/(main)/layout.tsx
src/app/(main)/not-found.tsx
src/app/(main)/page.tsx
src/app/(main)/planning-applications/[id]/feedback/layout.tsx
src/app/(main)/planning-applications/[id]/layout.tsx
src/app/(main)/planning-applications/[id]/page.tsx
src/app/(main)/planning-applications/[id]/thank-you/layout.tsx
src/app/actions/sanityClient.ts
src/app/not-found.tsx
src/components/about/index.tsx
src/components/process/index.tsx

[DSNPI-1141](https://tpximpact.atlassian.net/browse/DSNPI-1141)
This PR:
- Adds page titles
- `/not-found-page` - Page Not Found | Digital Site Notice
- `/` - Find planning applications near you | Digital Site Notice
- `/?postcode=12345` - Planning applications near 12345 | Digital Site Notice
- `/planning-applications/a988a178-74a7-4900-8caf-7358bf44bb0e` - 8-9 Spring Place London Camden NW5 3ER | Digital Site Notice
- `/planning-applications/a988a178-74a7-4900-8caf-7358bf44bb0e/feedback` - Feedback | 8-9 Spring Place London Camden NW5 3ER | Digital Site Notice
-  `/planning-applications/a988a178-74a7-4900-8caf-7358bf44bb0e/thank-you` - Comment submitted | 8-9 Spring Place London Camden NW5 3ER | Digital Site Notice
- Fixed `getApplicationById` returning `data: [{}]` it now returns …

DSNPI-1141 Add titles to pages

---

src/components/PageAccessibilityStatement/PageAccessibilityStatement.tsx

DSNPI-1105 / Accessibility statement (amendment)

---

src/components/PageAccessibilityStatement/PageAccessibilityStatement.tsx

DSNPI-1105 accessibility statement change
