- src/styles/home.scss
Minor style fix for mobile-view of electronic alert link to 'Sign up for alerts on applications near you' / `grid-button-signup` - using media queries (at bottom of file). I adjusted the existing `height: 42px;` style to only trigger when the viewport is at least 768 pixels wide, which typically covers tablets and desktops but excludes most mobile phones in portrait orientation.
This file has also been linted on save so the formatting has changed many lines of code.
**BEFORE:**
**AFTER:**
> Fix styling on electronic alert link

- src/components/process/index.tsx
Quick fix to amend language to include the word 'can': ‘People in the local community **can** share feedback……’'
> Amend language to include the word 'can'

- src/styles/application.scss
[Ticket 207](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?selectedIssue=DSNPI-207)
Quick style fix for button after QA found issue with mobile viewports. I was able to replicate issue by choosing Samsung Galaxy S8+ dimensions on the inspect window. This should now be resolved.
> Add style for mobile viewports

- __tests__/populate-button.test.js
- sanity/schemas/globalContent.ts
- sanity/schemas/planningApplication.ts
- src/components/populate-button/index.tsx
Implements a 'Fetch now' button that pulls data from OpenAPI into the planning application fields in Sanity, if the Integrations option in Global Content is set to OpenAPI. Based on @duncanheron 's proof of concept. 
The integration option is set to manual by default, and displays the option to select Open API in the Global Content section.
Pulls in the following data: `application_type, name, development_address, development_description, location - latitude, longitude, applicationDocumentsUrl.` If the fields have a value it will display on Sanity.
Additionally shows success/error messages to user based on the status of the fetch. If the application number is invalid it reminds the user to check it.
TODO: Test needs to be re-enabled with mocks. There is an issue that keeps re-appearing: …
> Pull content from Integration into the CMS

- __tests__/src/lib/dataService.test.ts
- src/lib/dataService.ts
- src/lib/sanityClient.ts
- src/pages/index.tsx
Refactors the search by postcode implementation with GROQ and distance queries. 
The user enters a postcode which is converted to latitude and longitude. Results are queried and ordered using GROQ `geo::distance` function that returns the distance between the user entered location and the location in the planning application schema. As this returns the distance in meters, it is then converted to miles and rounded.
The searched location state is maintained during pagination.
n.b: if a planning application does not have a location (latitude and longitude), it is not shown in the search results. Previously we added this to the end of the results but now it is no longer shown.
> Fix location search

- sanity/schemas/planningApplication.ts
Ticket: https://tpximpact.atlassian.net/browse/DSNPI-147?atlOrigin=eyJpIjoiYzkyNTQwYTdlY2Q4NGJkNGIxMDIyYTllZTkzMjI3YTMiLCJwIjoiaiJ9
We still can upload image with the same name (we don't use the name for anything, just for sanity display), but I create a validation that not allow to upload the same image twice
> add image name validation

- src/styles/home.scss
Page numbers were not aligned when a page was selected, this is now fixed.
> DSNPI 254 - Align page numbers

- sanity/schemas/planningApplication.ts
[Ticket 264](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?selectedIssue=DSNPI-264)
Quick fix to check for image array presence before running the validation that checks for duplicates. 
Validation error was blocking publishing without images - `image_gallery: Exception occurred while validating value: Cannot read properties of undefined (reading 'filter')`
> Gallery validation fix

- src/styles/home.scss
[Ticket 252](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?selectedIssue=DSNPI-252)
Minor change adding space between the planning application cards to align with the page grid width properly.
The first bulletpoint in the ticket is not required because the sizing of the header is bigger on the build than the figma design, which makes the spacing look the way it does.
> Content spacing

- __tests__/application.test.ts
- __tests__/applications.test.ts
- __tests__/comments.test.ts
- __tests__/components/questions.test.js
- __tests__/index.test.js
- __tests__/snapshot.js
- src/app/(main)/concern-info.tsx
- src/app/(main)/cookie-policy/page.tsx
- src/app/(main)/planning-applications/[id]/feedback/instructions.tsx
- src/app/(main)/planning-applications/[id]/thank-you/page.tsx
- src/app/actions/actions.ts
- src/components/feedback-information/index.tsx
- src/components/personal-details/index.tsx
- src/components/process/index.tsx
Ticket: https://tpximpact.atlassian.net/browse/DSNPI-337?atlOrigin=eyJpIjoiN2JmNWY5YmU2YmU1NGM0NmI4ZDAzNzcxMjdkNjU1NjAiLCJwIjoiaiJ9
The revalidateTag does not work with CMS. I wrapped getGlobalConfig inside react cache, in this case the fetching is happening one time and every other time we call the function is returning the cache.
> cache getGlobalContent

- src/app/(main)/planning-applications/[id]/page.tsx
Ticket: https://tpximpact.atlassian.net/browse/DSNPI-603?atlOrigin=eyJpIjoiMzE4YjBlMTJmYWExNDY2Y2EzZDI1ZmM3YTI5YTczODUiLCJwIjoiaiJ9
This ticket it's fixing the not found page when we have a wrong application. 
anything different then /planning-application/wrong-id will redirect to default 404, and this is caused my nextjs that does not support layout on roots app when we have to folders roots, in our case main and studio.
> fix not found application

- .github/workflows/send-event-staging.yml
We've started getting this error when events are dispatched to the deployment repo
```
{
"message": "Resource not accessible by integration",
"documentation_url": "https://docs.github.com/rest/repos/repos#create-a-repository-dispatch-event",
"status": "403"
}
```
> Update permissions to GITHUB_TOKEN for this action

- src/app/(main)/layout.tsx
- src/components/cookies/index.tsx
https://tpximpact.atlassian.net/browse/DSNPI-946
I'm not sure the cookies have ever worked on DSN? showCookieBanner and Cookie acceptance were set to `"true"`/`"false"` not `true`/`false` so the jsx would never have worked or always worked because a string is considered truthy
- fixed show/hide banner logic
- when accepting cookies the page now reloads to load in the analytics otherwise the analytics would only load after a page refresh or the users next visit
> DSNPI-946 dsn fix cookie banner buttons

- .github/workflows/main-branch-protection.yml
So if you're a plum like me I kept forgetting to change my base from `main` to `staging`, so the check was running only if the base was `main` and after I change it to `staging` that meant that the check will never run again and my tests will look as if they've failed when they haven't.
So I've updated the script to look at all target bases but we also need to include types, by default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened but the edited type is what will let it run again when I inevitably forget (again) to set the right base branch!
> BUGFIX: branch protection check failing

- __tests__/checkbox.test.js
- src/components/checkbox/index.tsx
- src/components/personal-details/index.tsx
- src/components/topics/index.tsx
- src/styles/06-components/_feedback.scss
https://tpximpact.atlassian.net/browse/DSNPI-999
The topic selection checkboxes we're flagged because they weren't grouped correctly.
- Updated topic selection to use https://design-system.service.gov.uk/components/checkboxes/
- Updated `Checkbox` component to just be a checkbox to be repeated - fixed issues with id, name etc
- Updated the consent confirmation  on the final page after the above changes were made
- I removed the accessibility tests from the Checkbox tests because its no longer a 'whole' thing so the tests would aways fail.
> DSNPI-999 DSN checkbox forms

- src/components/about/index.tsx
This PR makes the application page always have an h1, either the name or address of the application.
> Application page should always have h1

- src/components/button/index.tsx
- src/components/check-answers/index.tsx
[Ticket 1033](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?selectedIssue=DSNPI-1033)
This PR adds aria labels to the change buttons on the review answers page. This ensures it is descriptive enough for screen-readers to convey what is being changed.
Also changed the `<ButtonLink />` component to accept more props so that the aria-label is passed, along with any additional props it may receive.
> DSNPI 1033 / WCAG feedback - Change buttons

- __tests__/__snapshots__/snapshot.js.snap
- __tests__/input.test.js
- src/app/(main)/page.tsx
- src/components/ContentNoResult/ContentNoResult.tsx
- src/components/postcodeSearch/index.tsx
[Ticket 1029](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?selectedIssue=DSNPI-1029)
Following on from feedback, this PR now removes the postcode validation from the postcode search form in favour of just using the existing "No applications match your search" / no results state. Also added `role="alert"` to the `<ContentNoResult />` component.
> DSNPI 1029 / wcag feedback status messages

- src/components/govuk/Pagination/PageItem.tsx
[Ticket 1028](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?selectedIssue=DSNPI-1028)
Replaces the `&sdot;` with `&#x022EF;` so that the ellipsis is read out by screenreaders
> DSNPI 1028 - WCAG pagination

- src/components/comment/index.tsx
- src/components/text-area/index.tsx
- Change `<h2>` to `<h1>` on text area component.
- Fix text area validation bug by using immediate input value instead of potentially outdated state. Because state updates in React are asynchronous, that check was running before the new value was applied. This meant that even if you typed one character, `commentForm[question]` was still empty (or not updated yet), causing the validation error to trigger immediately.
> Accessibility fixes

- src/app/actions/sanityClient.ts
We're not using this param in the query, have removed to prevent future confusion!
> PlanningId isnt used in query

- src/app/actions/sanityClient.ts
[Ticket 1238](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?selectedIssue=DSNPI-1238)
This PR changes the default ordering from ordering by ID to ordering by _createdAt descending. This does not affect the ordering of applications when performing a postcode search, as that orders by postcode proximity.
> DSNPI - 1238/order applications from newest to oldest

- __tests__/components/feelings.test.js
- __tests__/components/topics.test.js
- __tests__/localstorage-validation.test.ts
- sanity/sanity.types.ts
- sanity/schemas/globalContent.ts
- src/app/(main)/cookie-policy/page.tsx
- src/app/(main)/planning-applications/[id]/feedback/instructions.tsx
- src/app/(main)/planning-applications/[id]/feedback/page.tsx
- src/app/(main)/planning-applications/[id]/page.tsx
- src/app/(main)/planning-applications/[id]/thank-you/page.tsx
- src/app/actions/actions.ts
- src/app/lib/application.tsx
- src/components/about/index.tsx
- src/components/check-answers/index.tsx
- src/components/comment/index.tsx
- src/components/feedback-information/index.tsx
- src/components/feelings/index.tsx
- src/components/personal-details/index.tsx
- src/components/questions/index.tsx
- src/components/topics/index.tsx
[Ticket 1216](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?jql=assignee%20%3D%2062a6f3cb6085950068acebf7&selectedIssue=DSNPI-1216)
[Ticket 1228](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?jql=assignee%20%3D%2062a6f3cb6085950068acebf7&selectedIssue=DSNPI-1228)
[Ticket 1237](https://tpximpact.atlassian.net/jira/software/projects/DSNPI/boards/15?jql=assignee%20%3D%2062a6f3cb6085950068acebf7&selectedIssue=DSNPI-1237)
This PR adds the cookie policy page to the DSN. It is similar to the DPR policy but with changes that are specific to the DSN. We also refactor the comment storage to use session storage instead of local storage.
Changes:
- Adds cookie policy content and conditionally display the comment cookies information if comments are …
> DSNPI-1216 & 1228  & 1237 / Cookie policy and updates to storing comment data
